version: '3.8'

services:
  db:
    image: mysql
    restart: always
    container_name: mysqldb
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: threadsclone
      MYSQL_USER: threadsclone
      MYSQL_PASSWORD: 123456
    ports:
      - '3307:3306'
    volumes:
      - ./mysql/db:/var/lib/mysql
    networks:
      - threadsclone-mysql

  threadsApp-be:
    image: threads-clone
    build: .
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/threadsclone?
      SPRING_DATASOURCE_USERNAME: threadsclone
      SPRING_DATASOURCE_PASSWORD: 123456
    ports:
      - '8080:8080'
    depends_on:
      - db
    networks:
      - threadsclone-mysql

networks:
  threadsclone-mysql:
